//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        public int IdFilm { get; set; }
        public string NameFilm { get; set; }
        public string Country { get; set; }
        public int ReleaseYear { get; set; }
        public string ImageFilm { get; set; }
    }
}
